# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts("Adding locations")
Location.create(name: 'Pittsburgh', trail: 'TRHT', mile_marker: 0, dist_from_DC: 334, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.4406247999999, longitude: -79.9958864)
Location.create(name: 'Homestead', trail: 'TRHT', mile_marker: 3, dist_from_DC: 331, dist_from_trail: 'on trail', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.4059025, longitude: -79.9119948)
Location.create(name: 'Hazelwood', trail: 'TRHT', mile_marker: 4, dist_from_DC: 330, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.4117223, longitude: -79.9444525999999)
Location.create(name: 'McKeesport', trail: 'GAP', mile_marker: 132, dist_from_DC: 316, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.3470671, longitude: -79.8641232)
Location.create(name: 'Boston', trail: 'GAP', mile_marker: 128, dist_from_DC: 312, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.3120141, longitude: -79.8231024)
Location.create(name: 'Greenock', trail: 'GAP', mile_marker: 126, dist_from_DC: 310, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 40.3132236, longitude: -79.804205)
Location.create(name: 'Dravo\'s Landing Camping', trail: 'GAP', mile_marker: 122, dist_from_DC: 306, dist_from_trail: '0.1 mi', location_type: 'campsite', state: 'PA', restaurant: false, grocery: false, snack: false, notes: '', latitude: 40.2893306, longitude: -79.7773917)
Location.create(name: 'Buena Vista', trail: 'GAP', mile_marker: 120, dist_from_DC: 304, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: false, grocery: true, snack: true, notes: '', latitude: 40.2772219999999, longitude: -79.799167)
Location.create(name: 'Sutersville', trail: 'GAP', mile_marker: 117, dist_from_DC: 301, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: false, snack: true, notes: '', latitude: 40.2361815999999, longitude: -79.799212)
Location.create(name: 'West Newton', trail: 'GAP', mile_marker: 114, dist_from_DC: 298, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.2097933, longitude: -79.7669884)
Location.create(name: 'Cedar Creek Park', trail: 'GAP', mile_marker: 110, dist_from_DC: 294, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: false, grocery: false, snack: true, notes: '', latitude: 40.1725369, longitude: -79.7706165)
Location.create(name: 'Smithton', trail: 'GAP', mile_marker: 110, dist_from_DC: 294, dist_from_trail: '2.2 mi W', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 40.1539613, longitude: -79.7411535)
Location.create(name: 'Cedar Creek Hiker Biker', trail: 'GAP', mile_marker: 110, dist_from_DC: 294, dist_from_trail: 'on trail', location_type: 'campsite', state: 'PA', restaurant: false, grocery: false, snack: false, notes: '', latitude: 41.2033216, longitude: -77.1945247)
Location.create(name: 'Belle Vernon', trail: 'GAP', mile_marker: 110, dist_from_DC: 294, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 40.1250725, longitude: -79.8664356)
Location.create(name: 'Perryopolis', trail: 'GAP', mile_marker: 103, dist_from_DC: 287, dist_from_trail: '1.7 mi SE', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 40.0870182, longitude: -79.750597)
Location.create(name: 'Layton', trail: 'GAP', mile_marker: 101, dist_from_DC: 285, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: false, grocery: false, snack: true, notes: 'snacks across river', latitude: 40.0903515, longitude: -79.7233744999999)
Location.create(name: 'Round Bottom Hiker Biker', trail: 'GAP', mile_marker: 100, dist_from_DC: 284, dist_from_trail: 'on trail', location_type: 'campsite', state: 'PA', restaurant: false, grocery: false, snack: false, notes: '', latitude: 41.2033216, longitude: -77.1945247)
Location.create(name: 'Dawson/Dickerson Run', trail: 'GAP', mile_marker: 96, dist_from_DC: 280, dist_from_trail: '4 blocks', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 40.0384638, longitude: -79.6777713)
Location.create(name: 'Dawson', trail: 'GAP', mile_marker: 94, dist_from_DC: 278, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: false, snack: true, notes: 'snacks across river', latitude: 40.0470186, longitude: -79.654484)
Location.create(name: 'Adelaide', trail: 'GAP', mile_marker: 92, dist_from_DC: 276, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: false, grocery: false, snack: true, notes: '', latitude: 40.0434074, longitude: -79.6239279999999)
Location.create(name: 'Rivers Edge Campground', trail: 'GAP', mile_marker: 92, dist_from_DC: 276, dist_from_trail: 'on trail', location_type: 'campsite', state: 'PA', restaurant: false, grocery: false, snack: false, notes: '', latitude: 40.041744, longitude: -79.625473)
Location.create(name: 'Connellsville', trail: 'GAP', mile_marker: 88, dist_from_DC: 272, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 40.0178522, longitude: -79.5894828)
Location.create(name: 'Dunbar', trail: 'GAP', mile_marker: 88, dist_from_DC: 272, dist_from_trail: '2 mi W side trail', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.9778528, longitude: -79.6144834999999)
Location.create(name: 'Ohiopyle', trail: 'GAP', mile_marker: 72, dist_from_DC: 256, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.871742, longitude: -79.4922606)
Location.create(name: 'Confluence', trail: 'GAP', mile_marker: 62, dist_from_DC: 246, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.8128547, longitude: -79.3567015)
Location.create(name: 'Harnedsville', trail: 'GAP', mile_marker: 61, dist_from_DC: 245, dist_from_trail: '0.5 mi SW', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.7975775, longitude: -79.3278119)
Location.create(name: 'Fort Hill', trail: 'GAP', mile_marker: 54, dist_from_DC: 238, dist_from_trail: '2.7 MI', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.8316303, longitude: -79.274227)
Location.create(name: 'Markleton', trail: 'GAP', mile_marker: 50, dist_from_DC: 234, dist_from_trail: '1.1 mi', location_type: 'town', state: 'PA', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.8606333, longitude: -79.2269756)
Location.create(name: 'Rockwood', trail: 'GAP', mile_marker: 43, dist_from_DC: 227, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.9156337, longitude: -79.1522514999999)
Location.create(name: 'Garrett', trail: 'GAP', mile_marker: 36, dist_from_DC: 220, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: false, grocery: false, snack: true, notes: '', latitude: 39.8631361, longitude: -79.0580823)
Location.create(name: 'Meyersdale', trail: 'GAP', mile_marker: 32, dist_from_DC: 216, dist_from_trail: '', location_type: 'town', state: 'PA', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.8136930999999, longitude: -79.024748)
Location.create(name: 'Mason-Dixon Campground', trail: 'GAP', mile_marker: 24, dist_from_DC: 208, dist_from_trail: 'On detour', location_type: 'campsite', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 38.9879976, longitude: -76.4664207)
Location.create(name: 'Frostburg', trail: 'GAP', mile_marker: 15, dist_from_DC: 199, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.6581424, longitude: -78.9283569999999)
Location.create(name: 'Mt Savage', trail: 'GAP', mile_marker: 11.2, dist_from_DC: 195.2, dist_from_trail: '1 mi', location_type: 'town', state: 'MD', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.6956417, longitude: -78.8797441999999)
Location.create(name: 'Cumberland', trail: 'C&O', mile_marker: 185, dist_from_DC: 185, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.6528654, longitude: -78.7625185)
Location.create(name: 'Evitts Creek Hiker-Biker', trail: 'C&O', mile_marker: 180, dist_from_DC: 180, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.624747, longitude: -78.739)
Location.create(name: 'Iron Mountain Hiker-Biker', trail: 'C&O', mile_marker: 175.4, dist_from_DC: 175.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.587423, longitude: -78.73279)
Location.create(name: 'Spring Gap Drive-in Camp', trail: 'C&O', mile_marker: 173.3, dist_from_DC: 173.3, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.56465, longitude: -78.718116)
Location.create(name: 'Pigmans Ferry Hiker-Biker', trail: 'C&O', mile_marker: 169.2, dist_from_DC: 169.2, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.538607, longitude: -78.641105)
Location.create(name: 'Oldtown', trail: 'C&O', mile_marker: 167, dist_from_DC: 167, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: false, grocery: true, snack: true, notes: '', latitude: 39.5416849, longitude: -78.6115064999999)
Location.create(name: 'Potomac Forks Hiker-Biker', trail: 'C&O', mile_marker: 164.8, dist_from_DC: 164.8, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.530388, longitude: -78.586919)
Location.create(name: 'Town Creek Hiker-Biker', trail: 'C&O', mile_marker: 162.1, dist_from_DC: 162.1, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.523542, longitude: -78.543055)
Location.create(name: 'Purslane Run Hiker-Biker', trail: 'C&O', mile_marker: 156.9, dist_from_DC: 156.9, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.534599, longitude: -78.463867)
Location.create(name: 'Paw Paw Walk-in Camp', trail: 'C&O', mile_marker: 156.2, dist_from_DC: 156.2, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.54419, longitude: -78.459803)
Location.create(name: 'Paw Paw', trail: 'C&O', mile_marker: 156, dist_from_DC: 156, dist_from_trail: '', location_type: 'town', state: 'WV', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.4601569, longitude: -78.4371726)
Location.create(name: 'Sorrel Ridge Hiker-Biker', trail: 'C&O', mile_marker: 154.1, dist_from_DC: 154.1, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.573573, longitude: -78.456614)
Location.create(name: 'Stickpile Hill Hiker-Biker', trail: 'C&O', mile_marker: 149.4, dist_from_DC: 149.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.583761, longitude: -78.403742)
Location.create(name: 'Devils Alley Hiker-Biker', trail: 'C&O', mile_marker: 144.5, dist_from_DC: 144.5, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.607259, longitude: -78.42998)
Location.create(name: 'Little Orleans', trail: 'C&O', mile_marker: 141, dist_from_DC: 141, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.625833, longitude: -78.386389)
Location.create(name: 'Indigo Neck Hiker-Biker', trail: 'C&O', mile_marker: 139.2, dist_from_DC: 139.2, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.627529, longitude: -78.360812)
Location.create(name: 'Cacapon Junction Hiker-Biker', trail: 'C&O', mile_marker: 133.6, dist_from_DC: 133.6, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.622329, longitude: -78.285109)
Location.create(name: 'Leopards Mill Hiker-Biker', trail: 'C&O', mile_marker: 129.8, dist_from_DC: 129.8, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.659077, longitude: -78.227774)
Location.create(name: 'White Rock Hiker-Biker', trail: 'C&O', mile_marker: 126.4, dist_from_DC: 126.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.682465, longitude: -78.198935)
Location.create(name: 'Hancock', trail: 'C&O', mile_marker: 124, dist_from_DC: 124, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.6989809, longitude: -78.1797292999999)
Location.create(name: 'Little Pool Hiker-Biker', trail: 'C&O', mile_marker: 120.4, dist_from_DC: 120.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.684678, longitude: -78.111361)
Location.create(name: 'Licking Creek Hiker-Biker', trail: 'C&O', mile_marker: 116, dist_from_DC: 116, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.651972, longitude: -78.050292)
Location.create(name: 'Big Pool', trail: 'C&O', mile_marker: 112.4, dist_from_DC: 112.4, dist_from_trail: '0.25 mi W', location_type: 'campsite', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.6237607, longitude: -78.0162934)
Location.create(name: 'McCoy\'s Ferry', trail: 'C&O', mile_marker: 110.4, dist_from_DC: 110.4, dist_from_trail: '0.1 mi', location_type: 'campsite', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.607899, longitude: -77.969529)
Location.create(name: 'North Mountain Hiker-Biker', trail: 'C&O', mile_marker: 110, dist_from_DC: 110, dist_from_trail: 'on trail', location_type: 'campsite', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.608857, longitude: -77.951257)
Location.create(name: 'Dam 5 Road', trail: 'C&O', mile_marker: 106, dist_from_DC: 106, dist_from_trail: '3.7 mi N', location_type: 'town', state: 'MD', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.617947, longitude: -77.9013993)
Location.create(name: 'Jordan Junction Hiker-Biker', trail: 'C&O', mile_marker: 101.3, dist_from_DC: 101.3, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.609366, longitude: -77.851569)
Location.create(name: 'Williamsport', trail: 'C&O', mile_marker: 100, dist_from_DC: 100, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: '', latitude: 39.6006523, longitude: -77.8205507999999)
Location.create(name: 'Cumberland Valley Hiker-Biker', trail: 'C&O', mile_marker: 95.2, dist_from_DC: 95.2, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.561955, longitude: -77.850432)
Location.create(name: 'Opequon Junction Hiker-Biker', trail: 'C&O', mile_marker: 90.9, dist_from_DC: 90.9, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.516812, longitude: -77.856612)
Location.create(name: 'McMahon’s Mill Campground', trail: 'C&O', mile_marker: 88.1, dist_from_DC: 88.1, dist_from_trail: 'On detour', location_type: 'campsite', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 38.9879976, longitude: -76.4664207)
Location.create(name: 'Big Woods Hiker-Biker', trail: 'C&O', mile_marker: 82.5, dist_from_DC: 82.5, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.493195, longitude: -77.79195)
Location.create(name: 'Horseshoe Bend Hiker-Biker', trail: 'C&O', mile_marker: 79.9, dist_from_DC: 79.9, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.486745, longitude: -77.776351)
Location.create(name: 'Killiansburg Cave Hiker-Biker', trail: 'C&O', mile_marker: 75.3, dist_from_DC: 75.3, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.457321, longitude: -77.796372)
Location.create(name: 'Shepherdstown', trail: 'C&O', mile_marker: 73, dist_from_DC: 73, dist_from_trail: '', location_type: 'town', state: 'WV', restaurant: true, grocery: true, snack: true, notes: 'very close to Sharpsburg', latitude: 39.4300996, longitude: -77.8041609)
Location.create(name: 'Sharpsburg', trail: 'C&O', mile_marker: 73, dist_from_DC: 73, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: 'very close to Shepherdstown', latitude: 39.4575994, longitude: -77.748882)
Location.create(name: 'Antietam Creek Walk-in Camp', trail: 'C&O', mile_marker: 69.4, dist_from_DC: 69.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.418111, longitude: -77.745528)
Location.create(name: 'Huckleberry Hill Hiker-Biker', trail: 'C&O', mile_marker: 62.9, dist_from_DC: 62.9, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.343126, longitude: -77.755102)
Location.create(name: 'Sandy Hook', trail: 'C&O', mile_marker: 60, dist_from_DC: 60, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: false, snack: true, notes: 'very close to Harpers Ferry', latitude: 39.325833, longitude: -77.710556)
Location.create(name: 'Harpers Ferry', trail: 'C&O', mile_marker: 60, dist_from_DC: 60, dist_from_trail: '', location_type: 'town', state: 'WV', restaurant: true, grocery: false, snack: true, notes: 'very close to Sandy Hook', latitude: 39.3253786, longitude: -77.7388818)
Location.create(name: 'Knoxville', trail: 'C&O', mile_marker: 60, dist_from_DC: 60, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.3270456, longitude: -77.6641576)
Location.create(name: 'Harper\'s Ferry', trail: 'C&O', mile_marker: 59.6, dist_from_DC: 59.6, dist_from_trail: '0.3 mi SE', location_type: 'campsite', state: 'WV', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.3253786, longitude: -77.7388818)
Location.create(name: 'Brunswick', trail: 'C&O', mile_marker: 55, dist_from_DC: 55, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: false, snack: false, notes: '', latitude: 39.3142682, longitude: -77.6277679)
Location.create(name: 'Brunswick Family Campground', trail: 'C&O', mile_marker: 54, dist_from_DC: 54, dist_from_trail: 'on trail', location_type: 'campsite', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.3072909, longitude: -77.616306)
Location.create(name: 'Bald Eagle Island Hiker-Biker', trail: 'C&O', mile_marker: 50.3, dist_from_DC: 50.3, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.299041, longitude: -77.557211)
Location.create(name: 'Lock House 28', trail: 'C&O', mile_marker: 49, dist_from_DC: 49, dist_from_trail: 'on trail', location_type: 'lock house', state: 'MD', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.2812547, longitude: -77.5477588)
Location.create(name: 'Point of Rocks', trail: 'C&O', mile_marker: 48, dist_from_DC: 48, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: false, grocery: true, snack: true, notes: '', latitude: 39.2758979, longitude: -77.5391815)
Location.create(name: 'Calico Rocks Hiker-Biker', trail: 'C&O', mile_marker: 47.6, dist_from_DC: 47.6, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.264252, longitude: -77.522488)
Location.create(name: 'Indian Flats Hiker-Biker', trail: 'C&O', mile_marker: 42.4, dist_from_DC: 42.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.227517, longitude: -77.455413)
Location.create(name: 'Dickerson', trail: 'C&O', mile_marker: 42.2, dist_from_DC: 42.2, dist_from_trail: '8 mi E', location_type: 'town', state: 'MD', restaurant: '', grocery: '', snack: '', notes: '', latitude: 39.2202562, longitude: -77.4242838999999)
Location.create(name: 'Marble Quarry Hiker-Biker', trail: 'C&O', mile_marker: 38.2, dist_from_DC: 38.2, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.179549, longitude: -77.492766)
Location.create(name: 'Whites Ferry', trail: 'C&O', mile_marker: 35, dist_from_DC: 35, dist_from_trail: '', location_type: 'town', state: 'MD', restaurant: true, grocery: true, snack: true, notes: 'restaurant and grocery in Leesburgh (5 mi)', latitude: 39.1548820999999, longitude: -77.5213646999999)
Location.create(name: 'Turtle Run Hiker-Biker', trail: 'C&O', mile_marker: 34.4, dist_from_DC: 34.4, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.1396, longitude: -77.515801)
Location.create(name: 'Chisel Branch Hiker-Biker', trail: 'C&O', mile_marker: 30.5, dist_from_DC: 30.5, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.090377, longitude: -77.462777)
Location.create(name: 'Horsepen Branch Hiker-Biker', trail: 'C&O', mile_marker: 26, dist_from_DC: 26, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.069679, longitude: -77.401911)
Location.create(name: 'Lock House 22', trail: 'C&O', mile_marker: 19.6, dist_from_DC: 19.6, dist_from_trail: 'on trail', location_type: 'lock house', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.047237, longitude: -77.274566)
Location.create(name: 'Swains Lock Hiker-Biker', trail: 'C&O', mile_marker: 16.6, dist_from_DC: 16.6, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 39.031128, longitude: -77.243621)
Location.create(name: 'Great Falls', trail: 'C&O', mile_marker: 15, dist_from_DC: 15, dist_from_trail: '', location_type: 'town', state: 'VA', restaurant: false, grocery: false, snack: true, notes: '', latitude: 38.9981652, longitude: -77.2883157)
Location.create(name: 'Marsden Tract Group Camp', trail: 'C&O', mile_marker: 11.5, dist_from_DC: 11.5, dist_from_trail: 'on trail', location_type: 'campsite', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 38.977121, longitude: -77.217758)
Location.create(name: 'Lock House 10', trail: 'C&O', mile_marker: 8.8, dist_from_DC: 8.8, dist_from_trail: 'on trail', location_type: 'lock house', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 38.971018, longitude: -77.159573)
Location.create(name: 'Lock House 6', trail: 'C&O', mile_marker: 5.4, dist_from_DC: 5.4, dist_from_trail: 'on trail', location_type: 'lock house', state: '', restaurant: false, grocery: false, snack: false, notes: '', latitude: 38.944822, longitude: -77.124211)
Location.create(name: 'Fletcher\'s Boat House', trail: 'C&O', mile_marker: 3, dist_from_DC: 3, dist_from_trail: '', location_type: 'town', state: '', restaurant: true, grocery: true, snack: true, notes: 'restaurant and grocery in Bethesda (4 mi)', latitude: 38.919284, longitude: -77.101884)
Location.create(name: 'Georgetown', trail: 'C&O', mile_marker: 1, dist_from_DC: 1, dist_from_trail: '', location_type: 'town', state: 'DC', restaurant: true, grocery: true, snack: true, notes: '', latitude: 38.9097057, longitude: -77.0653565)
Location.create(name: 'DC', trail: 'C&O', mile_marker: 0, dist_from_DC: 0, dist_from_trail: '', location_type: 'town', state: 'DC', restaurant: true, grocery: true, snack: true, notes: '', latitude: 38.9071923, longitude: -77.03687)

puts("Adding bikeshops")
Bikeshop.create(name: 'Thompson’s Boat Center', address: '2900 Virginia Ave, NW', location_id: 97, phone: '202-333-9543', bike_rental: true, website: 'http://www.thompsonboatcenter.com/')
Bikeshop.create(name: 'Bike the Sites', address: '901 G Street NW', location_id: 98, phone: '202-966-8662', bike_rental: true, website: 'http://www.bikethesites.com/')
Bikeshop.create(name: 'Big Wheel Bikes', address: '1034 33rd St NW', location_id: 97, phone: '202-337-0254', bike_rental: true, website: 'http://www.bigwheelbikes.com/')
Bikeshop.create(name: 'Revolution Cycles', address: '3411 M St NW', location_id: 98, phone: '202-965-3601', bike_rental: false, website: 'http://revolutioncycles.com/storelocator/clarendon-2.htm')
Bikeshop.create(name: 'Fletcher’s Boat Center', address: '4940 Canal Rd NW', location_id: 98, phone: '202-244-0461', bike_rental: true, website: 'http://www.fletcherscove.com/')
Bikeshop.create(name: 'Brunswick Hardware', address: '302 W Potomac St', location_id: 77, phone: '301-834-9207', bike_rental: false, website: 'http://discoverbrunswickmd.com/?dir-item=brunswick-hardware-and-sporting-goods')
Bikeshop.create(name: 'C&O Canal Biking', address: '24 W Potomac St', location_id: 77, phone: '301-834-5180', bike_rental: true, website: '')
Bikeshop.create(name: 'River & Trail Outfitters', address: '604 Valley Rd', location_id: 75, phone: '301-695-5177', bike_rental: true, website: 'http://www.rivertrail.com/index.php')
Bikeshop.create(name: 'Outfitter at Harpers Ferry', address: '106 Potomac St', location_id: 74, phone: '888-535-2087', bike_rental: true, website: 'http://www.theoutfitteratharpersferry.com/')
Bikeshop.create(name: 'River Riders', address: '408 Allstadts Hill Rd.', location_id: 74, phone: '800-326-7238', bike_rental: true, website: 'http://www.riverriders.com/')
Bikeshop.create(name: 'Reels & Wheels', address: '17328 Taylors Lndg Rd', location_id: 70, phone: '301-432-7281', bike_rental: false, website: 'https://www.facebook.com/pages/Reels-and-Wheels/316422291795284?rf=162853357065733')
Bikeshop.create(name: 'River City Cycles', address: '22 N Conococheague', location_id: 62, phone: '301-223-6733', bike_rental: false, website: 'http://rivercitycyclesinc.com/')
Bikeshop.create(name: 'C&O Bicycle', address: '9 S Pennsylvania Av', location_id: 54, phone: '301-678-6665', bike_rental: true, website: '')
Bikeshop.create(name: 'Cycles & Things', address: '165 N Centre St', location_id: 35, phone: '301-722-5496', bike_rental: false, website: '')
Bikeshop.create(name: 'Mountainside Bike Trs', address: '108 Decatur St', location_id: 35, phone: '800-459-0510', bike_rental: true, website: '')
Bikeshop.create(name: 'Adventure Sport (24/7)', address: '115 E Main St', location_id: 33, phone: '301-689-0345', bike_rental: true, website: '')
Bikeshop.create(name: 'Rockwood Trail House', address: '131 Rockdale Rd', location_id: 29, phone: '814-916-2453', bike_rental: true, website: '')
Bikeshop.create(name: 'Allegheny Recumbents', address: 'P.O. Box 160', location_id: 25, phone: '888-395-BIKE', bike_rental: true, website: '')
Bikeshop.create(name: 'Riversport', address: '885 River Rd.', location_id: 25, phone: '800-216-6991', bike_rental: true, website: '')
Bikeshop.create(name: 'Wilderness Voyageurs', address: 'PA381, 130 Garrett St', location_id: 24, phone: '800-272-4141', bike_rental: true, website: '')
Bikeshop.create(name: 'Lrl Highlands Rvr Tours', address: 'Sherman St', location_id: 24, phone: '800-472-3846', bike_rental: true, website: '')
Bikeshop.create(name: 'White Water Adv', address: 'Negley St', location_id: 24, phone: '724-329-8850', bike_rental: true, website: '')
Bikeshop.create(name: 'Ohiopyle Rec Rentals', address: 'PA381, Commercial St', location_id: 24, phone: '800-723-8669', bike_rental: true, website: '')
Bikeshop.create(name: 'Ohiopyle Trading Post', address: 'Negley St', location_id: 24, phone: '724-329-1450', bike_rental: true, website: '')
Bikeshop.create(name: 'Bikes Unlimited', address: '503 W. Crawford Av', location_id: 22, phone: '724-628-2453', bike_rental: true, website: '')
Bikeshop.create(name: 'Youghiogheny Rentals', address: '112 Railroad St', location_id: 19, phone: '724-529-2552', bike_rental: true, website: '')
Bikeshop.create(name: 'Cedar Creek Station', address: 'Cedar Creek Park', location_id: 14, phone: '724-872-5586', bike_rental: true, website: '')
Bikeshop.create(name: 'West Newton Bikes', address: '106 W Main St', location_id: 10, phone: '724-872-2185', bike_rental: true, website: '')
Bikeshop.create(name: 'River City Junction', address: '242 Sandy Dr', location_id: 6, phone: '412-754-0976', bike_rental: true, website: '')
Bikeshop.create(name: 'Boston Shoppes', address: '1903 Donner St', location_id: 5, phone: '412-751-6695', bike_rental: true, website: '')
Bikeshop.create(name: 'Trailside Treasures', address: '1910 Donner St', location_id: 5, phone: '412-896-6015', bike_rental: true, website: '')
Bikeshop.create(name: 'Burke Lee\'s', address: '2422 St David Dr', location_id: 4, phone: '412-754-1490', bike_rental: true, website: '')
Bikeshop.create(name: 'Golden Triangle Bike', address: 'on trail at 1st Ave', location_id: 1, phone: '412-600-0675', bike_rental: true, website: '')
Bikeshop.create(name: 'REI, Southside Works', address: '1 block from trail', location_id: 1, phone: '412-488-9410', bike_rental: false, website: '')
Bikeshop.create(name: 'Biketek Pittsburgh', address: '5839 Forbes Ave', location_id: 1, phone: '412-521-6448', bike_rental: true, website: '')
Bikeshop.create(name: 'Gatto Cycling & Fitness', address: '7501 Penn Ave', location_id: 1, phone: '412-731-9200', bike_rental: true, website: '')
Bikeshop.create(name: 'Top Gear', address: '986 Penn Circle South Suite 204', location_id: 1, phone: '412-362-8735', bike_rental: false, website: '')

puts("Adding campsites")
Campsite.create(name: 'Marsden Tract Group Camp', dist_from_trail: 'on trail', location_id: 93, campsite_type: 'Primitive', phone: '301-767-3731', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Swains Lock Hiker-Biker', dist_from_trail: 'on trail', location_id: 91, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Horsepen Branch Hiker-Biker', dist_from_trail: 'on trail', location_id: 89, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Chisel Branch Hiker-Biker', dist_from_trail: 'on trail', location_id: 88, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Turtle Run Hiker-Biker', dist_from_trail: 'on trail', location_id: 87, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Marble Quarry Hiker-Biker', dist_from_trail: 'on trail', location_id: 85, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Indian Flats Hiker-Biker', dist_from_trail: 'on trail', location_id: 83, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Calico Rocks Hiker-Biker', dist_from_trail: 'on trail', location_id: 82, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Bald Eagle Island Hiker-Biker', dist_from_trail: 'on trail', location_id: 79, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Brunswick Family Campground', dist_from_trail: 'on trail', location_id: 78, campsite_type: 'Public developed', phone: '301-834-8050', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Harpers Ferry Hostel (uphill)', dist_from_trail: '0.3 mi SE', location_id: 76, campsite_type: 'Tents at hostel', phone: '301-834-7652', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Huckleberry Hill Hiker-Biker', dist_from_trail: 'on trail', location_id: 72, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Antietam Walk-in Camp', dist_from_trail: 'on trail', location_id: 71, campsite_type: 'NPS primitive', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Killiansburg Cave Hiker-Biker', dist_from_trail: 'on trail', location_id: 68, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Horseshoe Bend Hiker-Biker', dist_from_trail: 'on trail', location_id: 67, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Big Woods Hiker-Biker', dist_from_trail: 'on trail', location_id: 66, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'McMahon’s Mill Campground', dist_from_trail: 'On detour', location_id: 65, campsite_type: 'Commercial', phone: '301-223-8778', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Opequon Junction Hiker-Biker', dist_from_trail: 'on trail', location_id: 64, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Cumberland Valley Hiker-Biker', dist_from_trail: 'on trail', location_id: 63, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Yogi Bear Jellystone Ground', dist_from_trail: '3 mi SE', location_id: 62, campsite_type: 'Commercial', phone: '800-421-7116', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Hagerstown/Antietam KOA', dist_from_trail: '2.5 mi NE', location_id: 62, campsite_type: 'Commercial', phone: '301-223-7571', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Jordan Junction Hiker-Biker', dist_from_trail: 'on trail', location_id: 61, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'North Mountain Hiker-Biker', dist_from_trail: 'on trail', location_id: 59, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'McCoy’s Ferry Drive-in Camp', dist_from_trail: '0.1 mi', location_id: 58, campsite_type: 'NPS primitive', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Ft Frederick State Park', dist_from_trail: '0.25 mi W', location_id: 57, campsite_type: 'Public developed', phone: '301-842-2155', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Licking Creek Hiker-Biker', dist_from_trail: 'on trail', location_id: 56, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Little Pool Hiker-Biker', dist_from_trail: 'on trail', location_id: 55, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'White Rock Hiker-Biker', dist_from_trail: 'on trail', location_id: 53, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Happy Hills Campground (steep)', dist_from_trail: '1 mi N', location_id: 54, campsite_type: 'Commercial', phone: '301-678-7760', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Leopards Mill Hiker-Biker', dist_from_trail: 'on trail', location_id: 52, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Cacapon Junction Hiker-Biker', dist_from_trail: 'on trail', location_id: 51, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Indigo Neck Hiker-Biker', dist_from_trail: 'on trail', location_id: 50, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Little Orleans Campground', dist_from_trail: '1.5 mi W', location_id: 49, campsite_type: 'Commercial', phone: '301-478-2325', shower: '', toilet: true, electricity: '')
Campsite.create(name: '15 Mile Creek Drive-in & group tent', dist_from_trail: 'on trail', location_id: 49, campsite_type: 'NPS primitive', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Devils Alley Hiker-Biker', dist_from_trail: 'on trail', location_id: 48, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Stickpile Hill Hiker-Biker', dist_from_trail: 'on trail', location_id: 47, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Sorrel Ridge Hiker-Biker', dist_from_trail: 'on trail', location_id: 46, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Paw Paw Walk-in Camp', dist_from_trail: 'on trail', location_id: 44, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Purslane Run Hiker-Biker', dist_from_trail: 'on trail', location_id: 43, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Town Creek Hiker-Biker', dist_from_trail: 'on trail', location_id: 42, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Potomac Forks Hiker-Biker', dist_from_trail: 'on trail', location_id: 41, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Pigmans Ferry Hiker-Biker', dist_from_trail: 'on trail', location_id: 39, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Spring Gap Drive-in Camp', dist_from_trail: 'on trail', location_id: 38, campsite_type: 'NPS primitive', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Iron Mountain Hiker-Biker', dist_from_trail: 'on trail', location_id: 37, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Evitts Creek Hiker-Biker (noise)', dist_from_trail: 'on trail', location_id: 36, campsite_type: 'Primitive, no cars', phone: '301-739-4200', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Cumberland YMCA (train noise)', dist_from_trail: '1.1 Mile  N', location_id: 35, campsite_type: 'Commercial', phone: '301 777-9622', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Trail Inn Campground', dist_from_trail: 'Up to Frostburg', location_id: 33, campsite_type: 'Commercial', phone: '301-689-6466', shower: true, toilet: true, electricity: true)
Campsite.create(name: 'Mason-Dixon Campground', dist_from_trail: 'On detour', location_id: 32, campsite_type: 'Commercial', phone: '814-634-5982', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Husky Haven Campground', dist_from_trail: 'on trail', location_id: 29, campsite_type: 'Commercial', phone: '814-926-2024', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Outflow Camping @ Yough Dam', dist_from_trail: '0.2 mi S', location_id: 25, campsite_type: 'Hiker-biker area', phone: '814-395-3944', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Paddler’s Lane Camp', dist_from_trail: '2 mi  N', location_id: 25, campsite_type: 'Commercial', phone: '814-395-9555', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Wendy World Campground', dist_from_trail: '2 mi S', location_id: 25, campsite_type: 'Commercial', phone: '814-926-5396', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Ohiopyle State Pk (up big hill)', dist_from_trail: 'Above trail', location_id: 24, campsite_type: 'Public developed', phone: '724-329-8591', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Connellsville North Trailhead', dist_from_trail: 'on trail', location_id: 22, campsite_type: 'Primitive', phone: ' ', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Rivers Edge Campground', dist_from_trail: 'on trail', location_id: 21, campsite_type: 'Commercial', phone: '724-628-4880', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Round Bottom Hiker Biker', dist_from_trail: 'on trail', location_id: 17, campsite_type: 'Primitive, no cars', phone: '724-872-5586', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Hazelbaker’s Campground', dist_from_trail: '1 mi across river', location_id: 15, campsite_type: 'Commercial, primitive', phone: '724-736-8155', shower: '', toilet: true, electricity: '')
Campsite.create(name: 'Cedar Creek Hiker Biker', dist_from_trail: 'on trail', location_id: 13, campsite_type: 'Primitive', phone: '724-872-5586', shower: false, toilet: true, electricity: false)
Campsite.create(name: 'Dravo\'s Landing Camping', dist_from_trail: '0.1 mi', location_id: 7, campsite_type: 'Primitive, no cars', phone: '724-872-5586', shower: false, toilet: true, electricity: false)

puts("Adding lodgings")
Lodging.create(name: 'Adams Inn B&B', dist_from_trail: '3 mi E', address: '1746 Lanier Place NW', location_id: 98, phone: '202-745-3600', notes: '')
Lodging.create(name: 'Dupont at the Circle', dist_from_trail: '2 mi NW', address: '1604 19th St NW', location_id: 98, phone: '202-332-5251', notes: '')
Lodging.create(name: 'Hotel Lombardy', dist_from_trail: '1.5 mi', address: '2019 Pennsylvania Ave NW', location_id: 98, phone: '202-828-2600', notes: '')
Lodging.create(name: 'Inn at Dupont Circle', dist_from_trail: '2 mi NW', address: '1312 19th St NW', location_id: 98, phone: '202-467-6777', notes: '')
Lodging.create(name: 'International Guest House', dist_from_trail: '5.5 mi', address: '1441 Kennedy St NW', location_id: 98, phone: '202-726-5808', notes: '')
Lodging.create(name: 'Marriott - Key Bridge', dist_from_trail: '1.1 mi S', address: '1401 Lee Hwy', location_id: 98, phone: '703-524-6400', notes: '')
Lodging.create(name: 'Tabard Inn', dist_from_trail: '2.3 mi W', address: '1739 N St NW', location_id: 98, phone: '202-785-1277', notes: '')
Lodging.create(name: 'Washington International Hostel', dist_from_trail: '1.5 mi NE', address: '1009 11th St NW', location_id: 98, phone: '202-737-2333', notes: '')
Lodging.create(name: 'Four Seasons Hotel', dist_from_trail: '3 blocks', address: '2800 Pennsylvania Av NW', location_id: 97, phone: '202-342-0444', notes: '')
Lodging.create(name: 'Georgetown Inn', dist_from_trail: '4 blocks', address: '1310 Wisconsin Av', location_id: 97, phone: '', notes: '')
Lodging.create(name: 'Georgetown Suites', dist_from_trail: 'backs on trail', address: '1111 30th St NW', location_id: 97, phone: '202-298-7800', notes: '')
Lodging.create(name: 'Georgetown Suites/Harbor Bldg', dist_from_trail: '1 block', address: '1000 29th St NW', location_id: 97, phone: '202-298-7800', notes: '')
Lodging.create(name: 'Inn of Rosslyn', dist_from_trail: '1.5 mi W', address: '1601 Arlington Blvd', location_id: 97, phone: '703-524-3400', notes: '')
Lodging.create(name: 'Melrose Hotel', dist_from_trail: 'backs on trail', address: '2430 Pennsylvania Av NW', location_id: 97, phone: '202-955-6400', notes: '')
Lodging.create(name: 'Monticello Hotel', dist_from_trail: '3 blocks', address: '1075 Thomas Jefferson St NW', location_id: 97, phone: '202-337-0900', notes: '')
Lodging.create(name: 'River Inn', dist_from_trail: '5 blocks', address: '924 25th St NW', location_id: 97, phone: '202-337-7600', notes: '')
Lodging.create(name: 'St Gregory', dist_from_trail: '8 blocks', address: '2033 M st NW', location_id: 97, phone: '202-530-3600', notes: '')
Lodging.create(name: 'St James', dist_from_trail: '5 blocks', address: '950 24th St NW', location_id: 97, phone: '202-457-0500', notes: '')
Lodging.create(name: 'The Latham', dist_from_trail: 'backs on trail', address: '3000 M St NW', location_id: 97, phone: '202-726-5000', notes: '')
Lodging.create(name: 'Washington Monarch Hotel', dist_from_trail: '3 blocks', address: '2301 M St NW', location_id: 97, phone: '202-429-2400', notes: '')
Lodging.create(name: 'Washington Suites at Georgetown', dist_from_trail: '2 blocks', address: '2500 Pennsylvania Av NW', location_id: 97, phone: '202-333-8060', notes: '')
Lodging.create(name: 'American Inn of Bethesda', dist_from_trail: '4 mi on trail', address: '8130 Wisconsin Av', location_id: 96, phone: '301-656-9300', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Bethesda Court Hotel', dist_from_trail: '4 mi on trail', address: '7740 Wisconsin Ave', location_id: 96, phone: '301-656-2100', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'DoubletreeHotel Bethesda', dist_from_trail: '4 mi on trail', address: '8120 Wisconsin Av', location_id: 96, phone: '301-652-2000', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Hilton Garden Inn - Bethesda', dist_from_trail: '4 miles on trail', address: '7301 Waverly St', location_id: 96, phone: '301-654-8111', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Hyatt Regency Bethesda', dist_from_trail: '4 mi on trail', address: 'One Bethesda Metro Center', location_id: 96, phone: '301-657-1234', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Lucy\'s Bed and Breakfast', dist_from_trail: '4 mi on trail', address: '9203 Wadsworth Dr', location_id: 96, phone: '301-530-7256', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Ramada Hotel - Bethesda', dist_from_trail: '4 mi on trail', address: '8400 Wisconsin Av', location_id: 96, phone: '301-654-1000', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Residence Inn - Bethesda', dist_from_trail: '4 mi on trail', address: '7335 Wisconsin Av', location_id: 96, phone: '301-718-0200', notes: 'take Capital Crescent trail 4mi to Bethesda')
Lodging.create(name: 'Lock Houses 6', dist_from_trail: 'on trail', address: 'on trail at milepost 5.4', location_id: 95, phone: '301-714-2233', notes: '')
Lodging.create(name: 'Lock Houses 10', dist_from_trail: 'on trail', address: 'on trail at milepost 8.8', location_id: 94, phone: '301-714-2233', notes: '')
Lodging.create(name: 'Rockwood Manor', dist_from_trail: '0.5 mi up', address: '11001 MacArthur Blvd', location_id: 92, phone: '301-299-5026', notes: '')
Lodging.create(name: 'Lock Houses 22', dist_from_trail: 'on trail', address: 'on trail at milepost 19.6', location_id: 90, phone: '301-714-2233', notes: '')
Lodging.create(name: 'Best Western - Leesburg', dist_from_trail: '6 mi S', address: '726 E Market', location_id: 86, phone: '703-478-1309', notes: '')
Lodging.create(name: 'Colonial Inn', dist_from_trail: '5 mi S', address: '19 S King St', location_id: 86, phone: '703-777-5000', notes: '')
Lodging.create(name: 'Comfort Inn Suites - Leesburg', dist_from_trail: '5 mi S', address: 'E Market St', location_id: 86, phone: '', notes: '')
Lodging.create(name: 'Days Inn - Leesburg', dist_from_trail: '6 mi S', address: '721 E Market St', location_id: 86, phone: '703-777-6622', notes: '')
Lodging.create(name: 'Norris House Inn', dist_from_trail: '4.3 mi SW', address: '108 Loudoun St SW', location_id: 86, phone: '703-777-1806', notes: '')
Lodging.create(name: 'Pleasant Springs Farm B&B', dist_from_trail: '8 mi E', address: '16112 Barnesville Road', location_id: 84, phone: '301-972-3452', notes: '')
Lodging.create(name: 'Idyll Time Farm', dist_from_trail: '6.1 mi SW', address: '43470 Evans Pond Rd', location_id: 81, phone: '703-443-2992', notes: '')
Lodging.create(name: 'Tarara Winery / B&B', dist_from_trail: '5.1 mi', address: '13648 Tarara Lane', location_id: 81, phone: '703-771-7100', notes: '')
Lodging.create(name: 'Lock Houses 28', dist_from_trail: 'on trail', address: 'on trail at milepost 49', location_id: 80, phone: '301-714-2233', notes: '')
Lodging.create(name: 'Georges Mill Farm B&B', dist_from_trail: '5 mi S', address: '11867 Georges Mill Rd', location_id: 77, phone: '540-822-5224', notes: '')
Lodging.create(name: 'Green Country Inn', dist_from_trail: '1.3 mi NE', address: '620 Souder Rd', location_id: 77, phone: '301-834-9151', notes: '')
Lodging.create(name: 'Lockkeepers Inn', dist_from_trail: '2 blocks', address: '11 S Maryland Av', location_id: 77, phone: '301-834-6026', notes: '')
Lodging.create(name: 'Lovettsville B&B', dist_from_trail: '3.9 mi', address: '38 South Loudoun Street', location_id: 77, phone: '540-270-6841', notes: '')
Lodging.create(name: 'Harpers Ferry Hostel', dist_from_trail: '1 mi uphill', address: '19123 Sandy Hook Rd', location_id: 73, phone: '301-834-7652', notes: '')
Lodging.create(name: 'Hillside Motel', dist_from_trail: '0.8 mi uphill', address: '19105 Keep Tryst Rd', location_id: 73, phone: '301-834-8144', notes: '')
Lodging.create(name: 'Angler\'s Inn', dist_from_trail: '0.9 mi', address: '867 Washington St', location_id: 74, phone: '304-535-1239', notes: '')
Lodging.create(name: 'Between the Rivers B&B', dist_from_trail: '0.8 mi', address: '597 E Ridge St', location_id: 74, phone: '304-535-2768', notes: '')
Lodging.create(name: 'Butler Burrel House', dist_from_trail: '1.2 mi', address: '', location_id: 74, phone: '', notes: '')
Lodging.create(name: 'Camp Hill Bed and Breakfast', dist_from_trail: '0.8 mi', address: '700 Washington St', location_id: 74, phone: '304-535-2657', notes: '')
Lodging.create(name: 'Canal House Cottage', dist_from_trail: '1.3 mi', address: '1226 Washington St', location_id: 74, phone: '304.535.2880', notes: '')
Lodging.create(name: 'Econo Lodge', dist_from_trail: '1.2 mi', address: '25 Union Street', location_id: 74, phone: '304-535-6391', notes: '')
Lodging.create(name: 'Harpers Ferry Guest House', dist_from_trail: '0.8 mi', address: '800 Washington St', location_id: 74, phone: '304-535-2101', notes: '')
Lodging.create(name: 'Jackson Rose B&B', dist_from_trail: '1.2 mi', address: '1167 W Washington St', location_id: 74, phone: '304-535-1528', notes: '')
Lodging.create(name: 'Laurel Lodge', dist_from_trail: '1.0 mi', address: '844 East Ridge Street', location_id: 74, phone: '304-535-2886', notes: '')
Lodging.create(name: 'Quality Hotel', dist_from_trail: '2.4 mi', address: '4328 William L. Wilson Fwy', location_id: 74, phone: '304-535-6302', notes: '')
Lodging.create(name: 'Teahorse Hostel', dist_from_trail: '1.4 mi', address: '1312 Washington St', location_id: 74, phone: '304-535-6848', notes: '')
Lodging.create(name: 'The Ledge House', dist_from_trail: '0.9 mi', address: '280 Henry Clay Street', location_id: 74, phone: '877-468-4236', notes: '')
Lodging.create(name: 'The Town\'s Inn', dist_from_trail: '0.4 mi', address: '179 High St', location_id: 74, phone: '877-489-2447', notes: '')
Lodging.create(name: 'Bavarian Inn', dist_from_trail: '0.5 mi NW', address: '164 Shepherd Grade Road', location_id: 69, phone: '304-876-2551', notes: '')
Lodging.create(name: 'Clarion Hotel - Shepherdstown', dist_from_trail: '1.6 mi W', address: '233 Lowe Drive', location_id: 69, phone: '304-976-7000', notes: '')
Lodging.create(name: 'Comfort Inn - Shepherdstown', dist_from_trail: '1.5 mi W', address: '70 Maddex Square Drive', location_id: 69, phone: '304-976-3160', notes: '')
Lodging.create(name: 'Mecklenburg Inn', dist_from_trail: '1 mi SW', address: '128 E German St', location_id: 69, phone: '304-876-2126', notes: '')
Lodging.create(name: 'The Cottage in Shepherdstown', dist_from_trail: '0.8 mi W', address: '316 W. German St.', location_id: 69, phone: '866-410-4482', notes: '')
Lodging.create(name: 'The Little Inn', dist_from_trail: '0.7 mi W', address: '201 W German St', location_id: 69, phone: '304-876-2208', notes: '')
Lodging.create(name: 'Thomas Shepherd Inn', dist_from_trail: '1 mi SW', address: '300 W German St', location_id: 69, phone: '304-876-3715', notes: '')
Lodging.create(name: 'Inn At Antietam', dist_from_trail: '2 mi E', address: '220 E Main St', location_id: 70, phone: '301-432-6601', notes: '')
Lodging.create(name: 'Jacob Rohrbach Inn', dist_from_trail: '2 mi E', address: '138 W Main St', location_id: 70, phone: '301-432-5079', notes: '')
Lodging.create(name: 'Mary Hill House', dist_from_trail: '3.4 mi NE', address: '211 East Main St', location_id: 70, phone: '240-329-1969', notes: '')
Lodging.create(name: 'CandleLight Inn', dist_from_trail: '0.4 mi W', address: '14 N Conococheague St', location_id: 62, phone: '301-223-7376', notes: '')
Lodging.create(name: 'Red Roof Inn - Williamsport', dist_from_trail: '1 mi N', address: '310 E Potomac St', location_id: 62, phone: '301-582-3500', notes: '')
Lodging.create(name: 'Breezee Hill Farm B&B', dist_from_trail: '3.7 mi N', address: '12140 St Paul Rd', location_id: 60, phone: '301-842-2608', notes: '')
Lodging.create(name: 'Americas Best Value Inn', dist_from_trail: '0.4 mi W', address: '2 Blue Hill Rd', location_id: 54, phone: '301-678-6108', notes: '')
Lodging.create(name: 'C&O Bicycle & Bunkhouse', dist_from_trail: 'across canal', address: '95 Pennsylvania Av', location_id: 54, phone: '301-678-6665', notes: '')
Lodging.create(name: 'Riverrun B&B', dist_from_trail: '2 blocks', address: '7 South Taney Street', location_id: 54, phone: '301-678-6150', notes: '')
Lodging.create(name: 'Super 8 - Hancock', dist_from_trail: '0.5 mi NW', address: '118 Limestone Road', location_id: 54, phone: '301-678-6101', notes: '')
Lodging.create(name: 'The 1828 Trail In', dist_from_trail: '1 block', address: '10 West Main St', location_id: 54, phone: '301-678-7227', notes: '')
Lodging.create(name: 'Buck Valley Ranch LLC', dist_from_trail: 'pickup', address: '1344 Negro Mountain Rd', location_id: 49, phone: '717-294-3759', notes: '')
Lodging.create(name: 'Little Orleans Lodge', dist_from_trail: '0.5 mi', address: '12814 Appel Rd', location_id: 49, phone: '301-478-2102', notes: '')
Lodging.create(name: 'Town Hill B&B', dist_from_trail: 'pickup', address: '31101 National Pike NE', location_id: 49, phone: '301-478-2794', notes: '')
Lodging.create(name: 'Best Western - Braddock', dist_from_trail: 'pickup', address: '1268 National Hwy', location_id: 35, phone: '301-729-3300', notes: '')
Lodging.create(name: 'Cumberland Inn and Spa', dist_from_trail: '8 blocks', address: '120 Green St', location_id: 35, phone: '240-362-7111', notes: '')
Lodging.create(name: 'Fairfield Inn - Cumberland', dist_from_trail: 'on trail', address: '21 North Wineow Street', location_id: 35, phone: '301-722-0340', notes: '')
Lodging.create(name: 'Holiday Inn - Cumberland', dist_from_trail: '5 blocks', address: '100 S George St', location_id: 35, phone: '301-724-8800', notes: '')
Lodging.create(name: 'Rocky Gap Lodge', dist_from_trail: 'Pickup', address: '16701 Lakeview Road NE', location_id: 35, phone: '301-784-8400', notes: '')
Lodging.create(name: 'The Bruce House Inn', dist_from_trail: '9 blocks', address: '201 Fayette Street', location_id: 35, phone: '301-777-8860', notes: '')
Lodging.create(name: 'The Inn on Decatur', dist_from_trail: '10 blocks', address: '108 Decaur Street', location_id: 35, phone: '240-727-7039', notes: '')
Lodging.create(name: 'Castle Bed & Breakfast', dist_from_trail: '1 mi', address: '15925 Mt Savage Rd (MD36)', location_id: 34, phone: '301-264-4645', notes: '')
Lodging.create(name: 'Charlies Motel & The Hurry Back Inn', dist_from_trail: '1 mi W', address: '220 W Main St', location_id: 33, phone: '301-689-6557', notes: '')
Lodging.create(name: 'Clarysville Motel', dist_from_trail: '4 mi E', address: '16300 National Highway SW', location_id: 33, phone: '301-689-9912', notes: '')
Lodging.create(name: 'Days Inn - Frostburg', dist_from_trail: '2 mi SE', address: '11100 New Georges Ck Rd (Rt 36)', location_id: 33, phone: '301-689-2050', notes: '')
Lodging.create(name: 'Failinger‘s Hotel Gunter', dist_from_trail: '4 blocks', address: '11 W Main St', location_id: 33, phone: '301-689-6511', notes: '')
Lodging.create(name: 'Frostburg Inn', dist_from_trail: '0.3 mi E', address: '147 E Main St', location_id: 33, phone: '301-689-3831', notes: '')
Lodging.create(name: 'Frostburg State University Conf & Event Center', dist_from_trail: '1.5 mi SE', address: '', location_id: 33, phone: '301-687-4020', notes: '')
Lodging.create(name: 'Hampton Inn - Frostburg', dist_from_trail: '2 mi SE', address: '11200 New Georges Ck Rd (Rt 36)', location_id: 33, phone: '301-689-1998', notes: '')
Lodging.create(name: 'Savage River Lodge', dist_from_trail: '11 miN will shuttle', address: '1600 Mt. Aetna Road', location_id: 33, phone: '301 689 3200', notes: '')
Lodging.create(name: 'Trail Inn B&B / Campground', dist_from_trail: '0.1 mi', address: '20 Depot Street', location_id: 33, phone: '301-689-6466', notes: '')
Lodging.create(name: 'Allegheny Trail Hostel', dist_from_trail: '5 blocks', address: '215 Main St', location_id: 31, phone: '814-634-0691', notes: '')
Lodging.create(name: 'Donges Drive-In & Motel', dist_from_trail: '5 blocks', address: 'Monument Sq', location_id: 31, phone: '814-634-5710', notes: '')
Lodging.create(name: 'Gram Gram\'s Place', dist_from_trail: '1 block', address: '508 Main St', location_id: 31, phone: '814-634-0461', notes: '')
Lodging.create(name: 'Levi Deal Mansion', dist_from_trail: '1 block', address: '301 Meyers Avenue', location_id: 31, phone: '814-289-7600', notes: '')
Lodging.create(name: 'Meyersdale B&B', dist_from_trail: 'on Trail', address: '510 Main St', location_id: 31, phone: '', notes: '')
Lodging.create(name: 'Morguen Toole Company', dist_from_trail: '4 blocks', address: '130 Center Street', location_id: 31, phone: '814-521-4359', notes: '')
Lodging.create(name: 'The Burgess House', dist_from_trail: '9 blocks', address: '219 North Street', location_id: 31, phone: '814-662-2436', notes: '')
Lodging.create(name: 'Yoder\'s Motel', dist_from_trail: '5 blocks', address: '106 Meyers Ave', location_id: 31, phone: '814-634-8791', notes: '')
Lodging.create(name: 'Garrett House Bed & Breakfast', dist_from_trail: '4 blocks', address: '508 Church Street', location_id: 30, phone: '814-634-7072', notes: '')
Lodging.create(name: 'Candlewood Cabin Rental', dist_from_trail: '11 mi N', address: '119 Lind Ln', location_id: 29, phone: '814-926-4433', notes: '')
Lodging.create(name: 'Country Dreams Bed and Breakfast', dist_from_trail: '6 mi', address: '882 Chippewa Rd', location_id: 29, phone: '814-926-4774', notes: '')
Lodging.create(name: 'Glades Pike Inn', dist_from_trail: '11 mi will shuttle', address: '2684 Glades Pike (Rt 31)', location_id: 29, phone: '814-443-4978', notes: '')
Lodging.create(name: 'Hostel on Main', dist_from_trail: '3 blocks', address: '506 Main St', location_id: 29, phone: '814-926-4546', notes: '')
Lodging.create(name: 'Husky Haven Guesthouse', dist_from_trail: '2 blocks', address: '440 Water Street', location_id: 29, phone: '814-926-2024', notes: '')
Lodging.create(name: 'Laurel Echo Farm Vacation', dist_from_trail: '5 miN will shuttle', address: '174 Cross Rd', location_id: 29, phone: '814-926-2760', notes: '')
Lodging.create(name: 'Log Haven B&B', dist_from_trail: '7 miNW will shuttle', address: '1322 Trent Rd', location_id: 29, phone: '814-352-8971', notes: '')
Lodging.create(name: 'Rockwood Trail House B&B', dist_from_trail: 'on trail', address: '131 Rockdale Rd', location_id: 29, phone: '814-926-4778', notes: '')
Lodging.create(name: 'Scenic View', dist_from_trail: '7 mi NW', address: '118 Scenic View Lane', location_id: 29, phone: '412-231-2979', notes: '')
Lodging.create(name: 'The Gingerbread House B&B', dist_from_trail: '1 block', address: '156 Rockdale Road', location_id: 29, phone: '814-926-2542', notes: '')
Lodging.create(name: 'Trenthouse B&B and Country Store', dist_from_trail: '7 mi will shuttle', address: '2008 Copper Kettle Hwy', location_id: 29, phone: '814-352-7713', notes: '')
Lodging.create(name: 'Four Seasons Guest Farm', dist_from_trail: '1.1 mi', address: '450 Porter Rd', location_id: 28, phone: '814-926-3572', notes: '')
Lodging.create(name: 'A Cottage at Campbell Farm', dist_from_trail: '2.7 MI', address: '1723 Fort Hill Road', location_id: 27, phone: '814-395-5335', notes: '')
Lodging.create(name: 'Hanna House B&B', dist_from_trail: '0.5 mi SW', address: '1790 Listonburg Rd', location_id: 26, phone: '814-395-9466', notes: '')
Lodging.create(name: 'RiveRest Bed and Breakfast', dist_from_trail: '1.3 mi N', address: '194 Weyand St', location_id: 26, phone: '814-395-3969', notes: '')
Lodging.create(name: 'Stepping Stone Farm B & B', dist_from_trail: '1.2 mi', address: '140 Stepping Stone Lane', location_id: 26, phone: '814-395-9988', notes: '')
Lodging.create(name: 'Bed & Breakfast by Benyak', dist_from_trail: '2.2 mi E', address: '188 Walnut St', location_id: 25, phone: '443-253-8706', notes: '')
Lodging.create(name: 'Casselman Overlook Guest House', dist_from_trail: '0.4 mi E', address: '726 Oden Street', location_id: 25, phone: '724 366 2503', notes: '')
Lodging.create(name: 'Cassleman Bridge Suites', dist_from_trail: '0.6 mi NE', address: '115 Ross St', location_id: 25, phone: '814-926-3357', notes: '')
Lodging.create(name: 'Colonial House Bed & Breakfast', dist_from_trail: '0.5 mi E', address: '639 Oden St', location_id: 25, phone: '814-395-3869', notes: '')
Lodging.create(name: 'Hanna House B&B', dist_from_trail: '2.9 mi E', address: '1790 Listonburg Rd', location_id: 25, phone: '814-395-9466', notes: '')
Lodging.create(name: 'Hartzell House', dist_from_trail: '4.4 miS will shuttle', address: '728 Main Street', location_id: 25, phone: '814-395-5248', notes: '')
Lodging.create(name: 'Paddler\'s Lane Retreat B&B', dist_from_trail: '2.5 mi NW', address: '255 Paddlers Lane', location_id: 25, phone: '814-395-9555', notes: '')
Lodging.create(name: 'Parker House', dist_from_trail: '0.3 mi N', address: '213 Yough St', location_id: 25, phone: '814-395-9616', notes: '')
Lodging.create(name: 'River’s Edge Cafe & B&B', dist_from_trail: '0.3 mi E', address: '203 Yough St', location_id: 25, phone: '814-395-5059', notes: '')
Lodging.create(name: 'RiveRest Bed and Breakfast', dist_from_trail: '2.4 mi E', address: '194 Weyand St', location_id: 25, phone: '814-395-3969', notes: '')
Lodging.create(name: 'Riverview Kitchenetttes', dist_from_trail: '', address: '', location_id: 25, phone: '814-395-5682', notes: '')
Lodging.create(name: 'Stepping Stone Farm', dist_from_trail: '3 miNE will shuttle', address: '140 Stepping Stone Lane', location_id: 25, phone: '814-395-9988', notes: '')
Lodging.create(name: 'That Dam Yough House', dist_from_trail: '0.2 mi N', address: '615 Jacobs Street', location_id: 25, phone: '804-350-6301', notes: '')
Lodging.create(name: 'The Bear Paw Cabin', dist_from_trail: '6.4 ni', address: '187 Mae West Rd', location_id: 25, phone: '540-882-3343', notes: '')
Lodging.create(name: 'The Confluence House B&B', dist_from_trail: '0.7 mi NW', address: '522 Oden St', location_id: 25, phone: '814-352-5778', notes: '')
Lodging.create(name: 'The House at Confluence', dist_from_trail: '0.5 mi NE', address: '415 Sterner St', location_id: 25, phone: '724-468-0058', notes: '')
Lodging.create(name: 'Wendy world Campground - Bunkhouse', dist_from_trail: '1.6 mi', address: '1523 Mae West Road', location_id: 25, phone: '724-329-4252', notes: '')
Lodging.create(name: 'Yough Treehouse', dist_from_trail: '0.8 mi SW', address: '926 River Road', location_id: 25, phone: '814-395-2001', notes: '')
Lodging.create(name: 'Falls Market and Inn', dist_from_trail: '2 blocks', address: '69 Main St', location_id: 24, phone: '724-329-4973', notes: '')
Lodging.create(name: 'Ferncliff Guest House', dist_from_trail: '3 blocks', address: '137 Grant Street', location_id: 24, phone: '', notes: '')
Lodging.create(name: 'Hummingbird Guest Nest of Ohiopyle', dist_from_trail: '8 blocks', address: '107 Blaine Street', location_id: 24, phone: '724-329-5301', notes: '')
Lodging.create(name: 'MacKenzie Guest House', dist_from_trail: '3 blocks', address: '134 Grant Street', location_id: 24, phone: '724-329-8531', notes: '')
Lodging.create(name: 'Ohiopyle Lodge', dist_from_trail: '5 blocks', address: '138 Grant St', location_id: 24, phone: '724-329-4452', notes: '')
Lodging.create(name: 'Quiet House B&B, Cottages, and Camping', dist_from_trail: 'pickup', address: '667 Elliatsville Rd', location_id: 24, phone: '724-366-7050', notes: '')
Lodging.create(name: 'PO Box 2', dist_from_trail: 'Trillium Lodge', address: '724 329 1000', location_id: 24, phone: '', notes: '')
Lodging.create(name: 'White Water Adventurers', dist_from_trail: '6 blocks', address: '6 Negley St', location_id: 24, phone: '724-329-8850', notes: '')
Lodging.create(name: 'Yough Guest House', dist_from_trail: '1 block', address: '28 Serman St', location_id: 24, phone: '', notes: '')
Lodging.create(name: 'Yough Plaza Hotel', dist_from_trail: '1 blocks', address: '28 Sherman St', location_id: 24, phone: '', notes: '')
Lodging.create(name: 'Cinderella Ice Cream Castle', dist_from_trail: '2 mi W side trail', address: '33 W Railroad Street', location_id: 23, phone: '724-603-2663', notes: '')
Lodging.create(name: 'Connellsville Bed & Breakfast', dist_from_trail: '6 blocks', address: '316 W. Crawford Avenue', location_id: 22, phone: '724-603-2533', notes: '')
Lodging.create(name: 'Melody Motor Lodge', dist_from_trail: '2.5 miN uphill', address: 'Rt 119 S', location_id: 22, phone: '724-628-9600', notes: '')
Lodging.create(name: 'Seams Like Home B&B', dist_from_trail: '4 mi will shuttle', address: '2010 Emerald Valley Rd', location_id: 22, phone: '724-984-1399', notes: '')
Lodging.create(name: 'The Greenwood House', dist_from_trail: '7 blocks', address: '226 S Eight Street', location_id: 22, phone: '724-570-0566', notes: '')
Lodging.create(name: 'Victorian Rose B&B', dist_from_trail: '3.3 mi W', address: '1044 Highland St', location_id: 22, phone: '724-628-5520', notes: '')
Lodging.create(name: 'River’s Edge Campground', dist_from_trail: 'on trail', address: '1101 Rivers Edge Rd', location_id: 20, phone: '724-628-4880', notes: '')
Lodging.create(name: 'Cochran House B&B', dist_from_trail: '4 blocks', address: 'Railroad and Griscom St', location_id: 18, phone: '724-529-2736', notes: '')
Lodging.create(name: 'Dawson River Guest House', dist_from_trail: '0.5 mi NW', address: '', location_id: 18, phone: '724 880-5625', notes: '')
Lodging.create(name: 'Linden Hall', dist_from_trail: '4 mi NW', address: '432 Linden Hall Rd', location_id: 18, phone: '724-529-7543', notes: '')
Lodging.create(name: 'Inn at Lenora\'s', dist_from_trail: '1.7 mi SE', address: '301 S Liberty St', location_id: 15, phone: '724-736-2509', notes: '')
Lodging.create(name: 'Comfort Inn - Belle Veron', dist_from_trail: '2.2 mi W', address: '4300 State Route 51 South at PA51 near I70', location_id: 12, phone: '724-929-3177', notes: '')
Lodging.create(name: 'Fairway Inn', dist_from_trail: '1.5 mi W', address: 'on PA981 near intersection of PA51 and I70', location_id: 12, phone: '724-929-6677', notes: '')
Lodging.create(name: 'Holiday Inn Belle Veron', dist_from_trail: '1.5 mi W', address: '827 Finley Rd (at PA51 near I70)', location_id: 12, phone: '724-929-4600', notes: '')
Lodging.create(name: 'Knotty Pine Motel', dist_from_trail: '1.5 mi W', address: '843 Finley Road at PA51 near I70', location_id: 12, phone: '724-929-8430', notes: '')
Lodging.create(name: 'Relax Inn', dist_from_trail: '1.5 mi W', address: '833 Finley Rd', location_id: 12, phone: '724-929-6770', notes: '')
Lodging.create(name: 'Bright Morning B&B', dist_from_trail: '3 blocks', address: '127 Jefferson Court', location_id: 10, phone: '724-872-0792', notes: '')
Lodging.create(name: 'Crossing Inn', dist_from_trail: '0.8 mi', address: '104 Robertson St', location_id: 10, phone: '724-872-4221', notes: '')
Lodging.create(name: 'Scarsdale Cottage Inn', dist_from_trail: '5 blocks', address: '208 Allison St', location_id: 10, phone: '724-872-2121', notes: '')
Lodging.create(name: 'John Butler House B&B', dist_from_trail: '1 mi W', address: '800 Rock Run Rd', location_id: 8, phone: '412-751-6670', notes: '')
Lodging.create(name: 'Trailside Treasures', dist_from_trail: 'on trail', address: '1908 Donner St', location_id: 5, phone: '412-751-6695', notes: '')
Lodging.create(name: 'Yough Shore Inn', dist_from_trail: '4 blocks', address: '1403 Boston Hollow Road', location_id: 5, phone: '412-754-0440', notes: '')
Lodging.create(name: 'Courtyard - West Homestead', dist_from_trail: 'on trail', address: '401 West Waterfront Drive', location_id: 2, phone: '412-462-7301', notes: '')
Lodging.create(name: 'Hampton Inn & Suites Pittsburgh-Downtown', dist_from_trail: '2 blocks', address: '1247 Smallman Street', location_id: 1, phone: '412-288-4350', notes: '')
Lodging.create(name: 'Hampton Inn University Center', dist_from_trail: '1 mi N', address: '3315 Hamlet St', location_id: 1, phone: '412-681-1000', notes: '')
Lodging.create(name: 'Hilton Garden Hotel University Place', dist_from_trail: '1 mi N', address: '3454 Forbes Ave', location_id: 1, phone: '412-683-2040', notes: '')
Lodging.create(name: 'Hilton Inn - Pittsburgh - Oakland', dist_from_trail: '0.7 mi', address: '3454 Forbes Avenue,', location_id: 1, phone: '412-683-2040', notes: '')
Lodging.create(name: 'Hilton Pittsburgh and Towers', dist_from_trail: 'on trail', address: '600 Commonwealth Place', location_id: 1, phone: '412-391-4600', notes: '')
Lodging.create(name: 'Holiday Inn Express Pittsburgh, South Side', dist_from_trail: 'on trail', address: '20 S 10th St', location_id: 1, phone: '', notes: '')
Lodging.create(name: 'Holiday Inn Select University Center', dist_from_trail: '1 mi N', address: '100 Lytton Ave', location_id: 1, phone: '412-682-6200', notes: '')
Lodging.create(name: 'Inn on Negley', dist_from_trail: '3.7 mi N', address: '703 S Negley Ave', location_id: 1, phone: '412-661-0631', notes: '')
Lodging.create(name: 'Morning Glory Inn', dist_from_trail: '0.6 mi SE', address: '2119 Sarah St', location_id: 1, phone: '412-431-1707', notes: '')
Lodging.create(name: 'Omni William Penn', dist_from_trail: '5 blocks', address: '530 William Penn Pl', location_id: 1, phone: '412-281-7100', notes: '')
Lodging.create(name: 'Pittsburgh Bed and Breakfast Association', dist_from_trail: '', address: '724-444-6300', location_id: 1, phone: '', notes: '')
Lodging.create(name: 'Quality Inn Oakland', dist_from_trail: '0.6 mi uphill', address: '3401 Blvd of Allies', location_id: 1, phone: '412-683-6100', notes: '')
Lodging.create(name: 'Sheraton Hotel - Pittsburgh', dist_from_trail: '1 block', address: '300 W Station Square', location_id: 1, phone: '412-261-2000', notes: '')
Lodging.create(name: 'SpringHill Suites- Pittsburgh - Southside', dist_from_trail: 'on trail', address: '2950 South Water St', location_id: 1, phone: '412-488-8003', notes: '')
Lodging.create(name: 'Sunnyledge Hotel', dist_from_trail: '2.5 mi N', address: '5124 Fifth Ave.', location_id: 1, phone: '412-683-5014', notes: '')
Lodging.create(name: '703 South Negley Av', dist_from_trail: 'The Inn on Negley', address: '412-661-0631', location_id: 1, phone: '', notes: '')
Lodging.create(name: 'The Inn on the Mexican War Streets', dist_from_trail: '11 blocks', address: '604 W North Avenue', location_id: 1, phone: '412-231-6544', notes: '')
Lodging.create(name: 'The New Parador Inn of Pittsburgh', dist_from_trail: '8 blocks', address: '939 Western Ave', location_id: 1, phone: '412.231.4800', notes: '')
Lodging.create(name: 'Westin Convention Cneter', dist_from_trail: '2 blocks', address: '1000 Penn Av', location_id: 1, phone: '412-281-3700', notes: '')
Lodging.create(name: 'Westin William Penn', dist_from_trail: '', address: '530 William Penn Pl', location_id: 1, phone: '412-281-7100', notes: '')


